import { cn } from "@/lib/utils";
import "./globals.css";
import Header from "@/components/header_and_footer/header";
import Footer from "@/components/header_and_footer/footer";
import { Toaster } from "react-hot-toast";
import { Inter as FontSans } from "next/font/google"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "HISI COSMETICS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <Toaster position="top-right" />
        <Header />
        <main>
          {children}
        </main>
        <Footer />

      </body>
    </html >

  );
}
