import { cn } from "@/lib/utils";
import "./globals.css";
import Header from "@/components/header_and_footer/header";
import Footer from "@/components/header_and_footer/footer";
import { Toaster } from "react-hot-toast";
import { Inter as FontSans } from "next/font/google"
import AuthContextProvider from "../context/AuthContext";
import NextTopLoader from "nextjs-toploader";
import { ReduxProvider } from "@/lib/store/provider";
import LoginModal from "@/components/ui/loginModal";





const inter = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "HISI COSMETICS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Toaster position="top-right" />
          <AuthContextProvider>
            <NextTopLoader
              color="#ffa600"
              initialPosition={0.08}
              crawlSpeed={200}
              height={5}
              crawl={true}
              showSpinner={true}
              easing="ease"
              speed={200}
              shadow={false}
              template='<div class="bar" role="bar"><div class="peg"></div></div> 
            <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
              zIndex={1600}
              showAtBottom={false}
            />
            <Header />
            <main>
              {children}
            </main>
            {/* .login_modal */}


            <LoginModal />
          </AuthContextProvider>
          <Footer />
        </ReduxProvider>
      </body>
    </html>

  );
}
