import SidebarSettings from "@/components/settings/settingsSidebar";

export const metadata = {
    title: "HISI SETTINGS",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <div className="bg-gray-200">
            <div className="grid grid-cols-4 w-full container gap-10 py-14 min-h-[90vh]">
                <div className="col-span-1">
                    <SidebarSettings />
                </div>
                <div className="col-span-3 settings_body">
                    {children}
                </div>
            </div>
        </div>

    )
}